---
swagger: "2.0"
info:
  description: ""
  version: "1.5.0"
  title: "TimeSeriesDataCapture"
  contact:
    name: "TimeSeriesDataCapture@gmail.com"
    email: "TimeSeriesDataCapture@gmail.com"
host: "localhost:8000"
basePath: "/apis"
tags:
- name: "Browse API"
  description: "Getting and postings components from server"
schemes:
- "http"
- "https"
paths:
  /Components:
    get:
      tags:
      - "Browse API"
      summary: "Gets IDs available for import"
      description: "Gets all the component IDs available for import"
      operationId: "getComponentIDs"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Array of component objects"
            items:
              type: "string"
              example: 'component_id'
              description: "specific component ID"
                 
        400:
          description: "Bad request"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    post:
      tags:
      - "Browse API"
      summary: "Posts component IDs for import"
      description: "Posts all the component IDs for import"
      operationId: "postComponentIDs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "componentIDs"
        required: true
        schema:
          type: "array"
          description: "Array of component objects"
          items:
            type: "string"
            example: 'component_id'
            description: "specific component ID"
      responses:
        200:
          description: "Success"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
  /Components/{componentID}:
    get:
      tags:
      - "Browse API"
      summary: "Get a specific component"
      description: "Get a specific imported component by component ID"
      operationId: "getComponent"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              id:
                type: 'integer'
                description: "Run ID"
              Date&Timestamp:
                type: 'integer'
                description: "Date and timestamp"
              TagCollection:
                type: "array"
                items:
                  type: "string"
                  example: 'tag'
                  description: "A tag"
              AnnotationCollection:
                type: "array"
                items:
                  type: "string"
                  example: "annotation"
                  description: "A annotation"
              Data:
                type: "object"
                properties:
                  Column:
                    type: "array"
                    items:
                      type: "integer"
                      example: "data_point"
                      description: "point of data"

        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    delete:
      tags:
      - "Browse API"
      summary: "Deletes a specific component"
      description: "Deletes a specific imported component by component ID"
      operationId: "deleteComponent"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    
    put:
      tags:
      - "Browse API"
      summary: "Deletes a specific component"
      description: "Deletes a specific imported component by component ID"
      operationId: "updateComponent"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      - in: "body"
        name: "component"
        required: true
        schema:
          type: "array"
          description: "Array of property and new values"
          items:
            type: "object"
            properties:
              property:
                type: "string"
                description: "component property"
              
              value:
                type: "integer"
                description: "new value"
              
      responses:
        200:
          description: "Success"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    
  /ComponentSearch:
    get:
      tags:
      - "Browse API"
      summary: "Searches for componenets"
      description: "Searches database for components that match search string"
      operationId: "componentSearch"
      parameters:
      - name: "search"
        in: "query"
        description: "Search request"
        required: true
        type: "string"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "pagesize"
        in: "query"
        description: "page size (number of components)"
        required: false
        type: "integer"
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            description: "Array of component objects"
            items:
              type: "string"
              example: 'component_id'
              description: "specific component ID"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
  /authenticate:
    get:
      tags:
      - "Browse API"
      summary: "Gets file storage token"
      description: "Retrieves file storage token login into file storage"
      operationId: "getAuthenticate"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            type: "integer"
            example: "token"
            description: "File storage token"
        400:
          description: ""
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    post:
      tags:
      - "Browse API"
      summary: "Sends file storage auth token'"
      description: "Sends storage auth token"
      operationId: "postAuthenticate"
      parameters:
      - in: "body"
        name: "fileStorageToken"
        required: true
        schema:
          type: "object"
          properties:
            storageToken:
              type: "integer"
              example: "storage_token"
              description: "token used to authorize storage"
            profileID:
              type: "integer"
              example: "profile_id"
              description: "Id of the user logged in"
              
      responses:
        200:
          description: "Success"
        401:
          description: "Unauthorized"
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
securityDefinitions:
  timeseries_admin_auth:
    type: "oauth2"
    authorizationUrl: "https://timeseriestest.eu.auth0.com/authorize"
    flow: "implicit"
    scopes:
      admin: "Full Access"

