---
swagger: "2.0"
info:
  description: ""
  version: "1.5.0"
  title: "TimeSeriesDataCapture"
  contact:
    name: "TimeSeriesDataCapture@gmail.com"
    email: "TimeSeriesDataCapture@gmail.com"
host: "localhost:8000"
basePath: "/apis"
tags:
- name: "Browse API"
  description: "Getting and postings components from server"
schemes:
- "http"
- "https"
paths:
  /Components:
    get:
      tags:
      - "Browse API"
      summary: "Gets IDs available for import"
      description: "Gets all the component IDs available for import"
      operationId: "getComponentIDs"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: ""
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
    post:
      tags:
      - "Browse API"
      summary: "Posts component IDs for import"
      description: "Posts all the component IDs for import"
      operationId: "postComponentIDs"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "componentIDs"
        required: false
        schema:
          $ref: "#/definitions/componentIDs"
      responses:
        200:
          description: "Success"
        400:
          description: ""
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
  /Components/{componentID}:
    get:
      tags:
      - "Browse API"
      summary: "Get a specific component"
      description: "Get a specific imported component by component ID"
      operationId: "getComponent"
      parameters:
      - name: "componentID"
        in: "path"
        description: "Component ID specifies which component to download "
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: ""
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
  /ComponentSearch:
    get:
      tags:
      - "Browse API"
      summary: "Searches for componenets"
      description: "Searches database for components that match search string"
      operationId: "ComponentSearch"
      parameters:
      - name: "search"
        in: "query"
        description: "Search request"
        required: true
        type: "string"
      - name: "offset"
        in: "query"
        description: "splits and removes the response array between 0 and offset "
        required: false
        type: "integer"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: ""
      security:
      - timeseries_admin_auth:
        - "admin"
      x-swagger-router-controller: "BrowseAPI"
securityDefinitions:
  timeseries_admin_auth:
    type: "oauth2"
    authorizationUrl: "https://timeseriestest.eu.auth0.com/authorize"
    flow: "implicit"
    scopes:
      admin: "Full Access"
definitions:
  componentIDs:
    type: "object"
    properties:
      ComponentIDs:
        type: "array"
        description: "Array component IDs"
        items:
          type: "string"
  inline_response_200_1:
    properties:
      Component:
        type: "object"
        description: "Component object"
        properties: {}
    example:
      Component: "{}"
  inline_response_200:
    properties:
      ComponentIDs:
        type: "array"
        description: "Array of component IDs"
        items:
          type: "string"
    example:
      ComponentIDs:
      - "ComponentIDs"
      - "ComponentIDs"
  inline_response_200_2:
    properties:
      Components:
        type: "array"
        description: "Array of component objects"
        items:
          type: "object"
          properties: {}
    example:
      Components:
      - "{}"
      - "{}"
